server:
  port: 10010 # 服务端口
spring:
  application:
    name: CollegeExamSystem # 服务名称
  main:
    allow-circular-references: true #允许循环依赖注入
  # mysql数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    # 本机地址
    url: jdbc:mysql://localhost/college_exam_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    # 服务器地址
#    url: jdbc:mysql://47.99.83.63:3306/college_exam_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
#    password: 123456
  # 全局时间配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # redis配置
  redis:
    database: 0
#    host: 47.99.83.63
    host: 192.168.239.128
    password: root
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 60000
# mybatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

# 日志配置
logging:
  # 日志级别
  level:
    root: info
  file:
    # 日志文件名格式
    name: /logs/${spring.application.name}.out.log
    # 最大日志文件大小（默认10MB）
    max-size: 10MB
    # 要保留的日志备份的总大小
    total-size-cap: 1GB
    # 保存存档日志文件的最大天数（默认为7天）
    max-history: 30
  pattern:
    # 日志记录格式[组件名称][时间戳][日志级别][类名.方法名][消息文本]
    file: CollegeExamSystem %d{yyyy-MM-dd HH:mm:ss.SSS} %p %C. %M %m %n
    # 根据文档大小归档，超过2KB自动归档，次日启动服务时也会自动扫描
    rolling-file-name: /logs/%d{yyyyMMdd}/${spring.application.name}.out.log.%d{yyyy-MM-dd}.%i.gz


